//
// Created by Stephen Samuelson on 9/7/22.
//

#ifndef CPSC1021LAB1RETIREMENTCALCULATOR_COMPOUNDCALC_H
#define CPSC1021LAB1RETIREMENTCALCULATOR_COMPOUNDCALC_H

double compoundCalc(double, double, int);

#endif //CPSC1021LAB1RETIREMENTCALCULATOR_COMPOUNDCALC_H
